### ISSUE TITLE
cctbx refinement befor mozyme refinement

### ISSUE THREAD

**Issue by zhengmin317** [qrefine/qr-tests-cluster#1]
The GLN (ball and bond shape in the following figure) from folder 03 (after phenix.refine, adding hydrogen and structure completion) is distorted.
Moapc(mozyme) could not reach convergence.
![image](https://cloud.githubusercontent.com/assets/16145132/19556051/ade0d5ee-96bf-11e6-9f42-90bad175ca70.png)

One possible solution:
CCTBX refinement may fix distorted structure.

**Comment by mpwaller** [comment]
ok, thanks for the info, keep us updated.

**Comment by pafonine** [comment]
Hi Min,

thanks! A small suggestion though..

The folder 03 contains two PDB files. Could you please be more accurate 
telling 1) what PDB file you are looking at, and 2) what chain ID and 
residue number that GLN belongs to?

Of course I can do some detective work and try to match your figure 
against two files and then try to guess what GLN out of a few dozens you 
are focusing on... but that will take me hours and believe me or not, 
but I have better things to do in next few hours before I go offline.

Anyways, if it is distorted after phenix.refine then this likely means 
a) there is something terribly bad with this residue in input file, and 
b) nothing else will fix it unless we make inputs meaningful to begin 
with. Also, could it be that it gets damaged during processing steps 
(folders 02 and 03)? How it looks like in folder 01 (right after 
phenix.refine) and in folder 00 (original from PDB)?

Cheers,
Pavel

**Comment by zhengmin317** [comment]
Hi Pavel,

It's 3dtj. GLN179 chain A and GLN179 chain C.

The damage happens in folder 01 and folder 03.

After Q|R cctbx refinement of 3dtj in folder 03, the damage of GLN does 
not exist.

**Comment by pafonine** [comment]
Hi Min,

you are correct, it is damaged. Very nice catch, thanks! Unfortunately, 
I can't investigate this right now. However, I found that not using a 
particular option where producing refined files in 01 stops this from 
happening.

All it means for us is that we need to re-do files in 01 (re-run 
phenix.refine) and then update all other files in folders 02,03 etc.

I'm trying to do it right now.

Pavel

**Comment by pafonine** [comment]
Hi Min,

heads-up..

I'm about to replace files in 01 now. This means we need to discard all 
files in 02, 03, etc, and re-do them based on updated 01.

Pavel

**Comment by pafonine** [comment]
All done. Here is what I did:
- updated 01_run_phenix_refine file;
- re-ran refinements in 01 using updated 01_run_phenix_refine file.

Could you please:
- check if 3dtj is OK now?
- remove and re-create files in 02, 03.
- remove 04_results_cctbx because this is not what we planned and agreed 
  upon in README.md, and therefore it creates confusion.

Thanks,
Pavel
