### ISSUE TITLE
3UJ4

### ISSUE THREAD

**Issue by zhengmin317** [qrefine/qr-tests-cluster#3]
The charge value of 3UJ4 [https://github.com/qrefine/qr-tests-cluster/blob/master/02/3uj4_complete.pdb](https://github.com/qrefine/qr-tests-cluster/blob/master/02/3uj4_complete.pdb) from charges.py in qr-core is 47.
The TeraChem single point calculation of 3UJ4 says ([3uj4_complete.txt](https://github.com/qrefine/qr-tests-cluster/files/675357/3uj4_complete.txt)):
 "Incorrect molecular charge or spin multiplicity"

The error maybe from the following two:
1. Hydrogens are not in the appropriate positions.
![h_pos](https://cloud.githubusercontent.com/assets/16145132/21519405/0159fd28-cced-11e6-829c-a3195d9d2065.png)

2. All  histidine  are protonated.
![his](https://cloud.githubusercontent.com/assets/16145132/21519433/53812b3a-cced-11e6-87f5-a887093d9bcd.png)

**Comment by mpwaller** [comment]
fixed
